version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqls2022
    user: root
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql/data
    restart: always

  dotnet_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_aspnet_app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DockerConnection=Server=sqlserver;Database=JwtTest;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_SECRET}
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    restart: always

volumes:
  mssql_data:
